#!/bin/bash
#
# setup iptables. Overwrites existing tables
#
if [ $(id -u) -ne 0 ]; then
	echo "execute as root"
	exit 1
fi
(
	#this restores table settings upon reboot
	export DEBIAN_FRONTEND=noninteractive 
	apt-get install iptables-persistent
)

cat<< TABLE_END |
# Generated by iptables-save v1.4.21 on Fri May 27 08:42:29 2016
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [216:23893]
:REJECT_AND_LOG - [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m tcp --dport 80 -j ACCEPT 
-A INPUT -p tcp -m tcp --dport 443 -j ACCEPT 
-A INPUT -s 155.0.0.0/8 -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -s 10.0.0.0/8 -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-proto-unreachable
-A FORWARD -j REJECT_AND_LOG
-A REJECT_AND_LOG -m limit --limit 2/min -j LOG --log-prefix "iptables-reject: "
-A REJECT_AND_LOG -j REJECT --reject-with icmp-host-prohibited
COMMIT
# Completed on Fri May 27 08:42:29 2016
TABLE_END
iptables-restore

#
#store settings
#
invoke-rc.d iptables-persistent save

