#!/bin/bash
# gcw 6/16/2017 Set up angular on Ubuntu 16.04
if [ $(id -u) -ne 0 ]; then
	echo "Run as root"
	exit 1
fi

#need the latest version of Node

echo deb https://deb.nodesource.com/node_6.x xenial main > /etc/apt/sources.list.d/nodesource.list
echo deb-src https://deb.nodesource.com/node_6.x xenial main >> /etc/apt/sources.list.d/nodesource.list
wget -O - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
apt update

apt install nodejs 
npm install -g @angular/cli
npm install 
ng build -prod 
